project:
  output-dir: _site/dev
  resources:
    - quarto-wizard-dev.vsix

website:
  site-url: "https://m.canouil.dev/quarto-wizard/dev"
  announcement:
    icon: exclamation-circle
    dismissable: false
    content: "**Development** - This documentation is for the [development version of Quarto Wizard](quarto-wizard-dev.vsix). For the stable version, please visit [the main documentation](https://m.canouil.dev/quarto-wizard)."
    type: warning
    position: above-navbar
